apiVersion: v1
kind: Pod
metadata:
  namespace: aws
  name: aws-consumer
spec:
  containers:
    - name: aws-consumer-skaffold
      # this will be replaced by skaffold
      image: 'docker.openraven.io/open/aws-discovery:latest'
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      env:
        - name: SPRING_PROFILES_ACTIVE
          value: default,prod,consumer
        - name: GREMLIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: odb-orientdb-secret
              key: root-password
  # in lieu of Cron
  restartPolicy: OnFailure
